### PR TITLE
Make tests concurrency-safe

### PR DESCRIPTION
**Pull request by rotty**
This is a follow-up PR to #7 and #8; I'll rebase it if/when those go in -- please ignore the commits introduced by PR #7 and #8 for the purposes of reviewing this PR.

### CODE REVIEW

**Comment by staktrace** [comment]
This also looks good, thanks!

**Comment by staktrace** [comment]
Ditto here on rebasing

**Comment by rotty** [comment]
Rebased.

**Comment by staktrace** [comment]
Thanks for all the patches!

**Pull request merged**
